0412 DB one step further/01_template/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

0412 DB one step further/01_template/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

0412 DB one step further/01_template/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
#
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_POST, require_safe, require_http_methods
from .forms import CustomUserCreationForm, CustomUserChangeForm

from django.contrib.auth import get_user_model


# Create your views here.
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()

    context = {'form': form}
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('articles:index')

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index') 
    else:
        form = CustomUserCreationForm()
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['POST'])
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('articles:index')

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index') 
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {'form': form}
    return render(request, 'accounts/update.html', context)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index') 
    else:
        form = PasswordChangeForm(request.user)
    context = {'form': form}
    return render(request, 'accounts/change_password.html', context)


def profile(request, username):
    person = get_user_model().objects.get(username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        person = get_user_model().objects.get(pk=user_pk)
        # 자기자신이랑 다른 사람이어야 팔로우가 의미 있다
        # 지금 팔로우 상태라면 언팔
        # 지금 언팔 상태라면 팔로우
        if person != request.user:
            # 저 사람의 팔로워 목록에 request한 유저가 존재하면 언팔
            if person.followers.filter(pk=request.user.pk).exists():
                person.followers.remove(request.user)
            # 존재하지 않으면 follow
            else:
                person.followers.add(request.user)
        # 그 사람의 프로필 페이지에서 동작하는거니까 거기로 redirect!!
        return redirect('accounts:profile', person.username)
    return redirect('accounts:login')

0412 DB one step further/01_template/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
  <h1> {{ person.username }}님의 프로필</h1>

  <div>
    팔로잉 : {{ person.followings.count }} | 팔로워 : {{ person.followers.count }}
  </div>
  <form action="{% url 'accounts:follow' person.pk %}" method="POST">
    {% csrf_token %}
    {% comment %} 팔로우 하고 있으면 언팔 버튼, 아니면 반대로 {% endcomment %}
    {% if request.user in person.followers.all %}
      <button type="submit" class="btn btn-danger">언팔로우</button>
    {% else %}
      <button type="submit" class="btn btn-success">팔로우</button>
    {% endif %}
  </form>

  <hr>

  <h5> {{ person.username }}님이 작성한 게시글 </h5>
  {% for article in person.article_set.all %}
    {% comment %} <div><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></div>   {% endcomment %}

    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ article.title }}</h5>
        <p class="card-text">{{ article.content }}</p>
        <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">자세히 보기</a>
      </div>
    </div>
  {% endfor %}
  <br><br><br>

  <h5>{{ person.username }}님이 좋아한 게시글</h5>
  {% for article in person.like_articles.all %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ article.title }}</h5>
        <p class="card-text">{{ article.content }}</p>
        <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">자세히 보기</a>
      </div>
    </div>
  {% endfor %}
  <br><br><br>

  <a href="{% url 'articles:index' %}" class="btn btn-success">목록보기</a>

{% endblock content %}